src/tooltip/tooltip.js

IE8's TextRectangle object is read-only, causing an exception inside
angular.extend.  Copying the values of the object into a new object
allows the properties to be used inside angular.extend and fixes issue
#1447.

fix(tooltip): copy properties of bounding rectangle to support IE8

---

src/popover/docs/popover.demo.html
src/popover/docs/popover.demo.js

Popover uses 'click' trigger by default and when using the service to show
the popover as a result of clicking the associated element, it would cause
the popover to toggle and hide immediately.
Closes #1453

Update doc to show proper usage of $popover

---

src/modal/modal.js

Force the modal positioning and z-index to overcome bootstraps 3.3.0 change of location.
Fixes #1263

fix(backdrop): force modal backdrop position and z-index (fixes #1263)

---

src/tooltip/tooltip.js

When iterating the properties on the return value of getBoundingRect, hasOwnProperty is returning false causing the properties to not be copied into the new rect object.
Since the return value of getBoundingRect is frozen, we can safely remove the hasOwnPropertyCheck.  This should finally fully address #1447.

fix(tooltip): remove hasOwnProperty when iterating getBoundingRect

---

src/popover/docs/popover.demo.js

$popover service sample was calling .hide() instead of .toggle(), so popover would never show.
Fixes #1514

docs(popover): fix $popover service sample call

---

src/helpers/date-parser.js
src/helpers/test/date-parser.spec.js

This will be a fix for #1897.
However, I'm having some trouble coming up with a regular expression to cope with escaped quotes inside the literals, i.e. ```3 '0''clock'```, so it's still not finished.
Help anyone?

Fix date parser literals

---

src/helpers/date-parser.js
src/helpers/test/date-parser.spec.js

Re-added a modified escapeReservedSymbols to support special regex characters inside the format string. Don't know what characters should be supported, I added some of the most used in regex, besides the ones that already existed.
This will probably only be relevant for very special edge cases.

fix(dateParser): ignore regex special characters inside literals

---

src/aside/test/aside.spec.js
src/modal/modal.js
src/modal/test/modal.spec.js

feat(modal): set incremental z-index value for modals and asides to allow for stacking
The number of active modals and asides are tracked in order to set a `z-index` value that will allow those elements to be on top of each other.
Currently, if two asides are shown at the same time, clicking the backdrop will hide the aside that is below the one above.  Also, the backdrop of the second aside is below the first aside.

feat(modal): set incremental z-index value for modals and asides to allow for stacking

---

src/dropdown/dropdown.js

Prevent a null pointer exception when overriding the default template while using the dropdown without setting the `bs-dropdown` attribute.
```html
<div bs-dropdown data-template-url="something.html" />
```

fix(dropdown) prevent null pointer exception w/o inline template

---

src/modal/modal.js
src/modal/test/modal.spec.js

Add the `size` option for modals, which supports “sm” and “lg” as values. These correspond to Bootstrap’s pre-configured “modal-sm” and “modal-lg” classes.

feat(modal): support modal size option

---

src/typeahead/test/typeahead.spec.js
src/typeahead/typeahead.js

feat(typeahead): allow disabling of a filter to returned unfiltered results
The `bs-typeahead` directive will allow the `data-filter=""` attribute to take a
false value, which indicates that there should be no filtering of results.
Currently, the results are filtered by `bsAsyncFilter` by default, which may cause
undesired behaviour when retriving results from a remote source.
closes #2058 #2059

feat(typeahead): allow disabling of a filter

---

src/typeahead/typeahead.js

currently, when finishing text input, blur then focus and begin typing at another point
in the text (e.g. the beginning), the cursor will move to the end of the text after
inserting a new character.
now, the cursor will move to after the new character typed (normal behaviour)
closes: #1083 #1837 #1448

fix(typeahead): stop the cursor from jumping to the end of the input upon refocus

---

src/modal/docs/modal.demo.html
src/modal/modal.js
src/modal/test/modal.spec.js

This PR introduces a configurable z-index for modals. Replaces the stale and outdated #1788.
The modal z-index value defaults to 1050 - the backdrop value is decremented by 10.

feat(modal): configurable z-index

---

src/button/button.js

use ngModelController `$viewValue` and not `$modelValue` because the `isActive` state (and so active class of buttons) should be synchronized with viewValue.
For example, if a ngModelOptions is used with debouncing, `$modelValue` still equals the previous value on `$render` execution
That's a fix for #2164. Here is a fiddle using patch : https://jsfiddle.net/elkami/pkj3x9xr/
Thanks for review

fix for bsCheckbox and bsRadio: use $viewValue instead of $modelValue for setting isActive state

---

src/select/select.js
src/select/test/select.spec.js

On touch devices a click event is triggered on touchstart on an entry of the select list.
Trigger this emulated click not on the event.target but on the closest parent that is an anchor tag, where the click event triggers the select action.
Fix #2047 and #1580

fix($select): trigger click on closest anchor tag

---

src/modal/modal.js
src/modal/test/modal.spec.js

fix scrollbar issues on stacked modals removing class modal-open from body only when the last modal is closed
closes mgcrea/angular-strap#2153

fix($modal): fix scrollbar on stacked modals

---

src/tooltip/tooltip.js

- Checks whether the tooltip exists before applying animations to it

fix(tooltip): TypeError: Cannot read property 'remove' of null" 

---

src/datepicker/datepicker.js
src/datepicker/datepicker.tpl.html

On (mobile) Safari ng-click is triggered even when a button is disabled.
Fix: Pass disabled state to $select so we can check before setting clicked
date.

fix(datepicker): disable selecting disabled dates on iOS

---

index.js
package.json

Gives the ability to require('angular-strap') with no conflicts or errors on npm projects.
The templates are already include.
ex:
``` javascript
var angularStrap = require('angular-strap');
angular
.module('app', [
angularStrap
]);
```

Support for npm with templates included

---

docs/styles/main.less
src/typeahead/test/typeahead.spec.js
src/typeahead/typeahead.js

Add function to update scrollTop property on $typeahead.$element when avtive entry leaves visible window of the scrollable container ($typeahead.$element).
Should fix issues
- #1623 and
- #1021.
I tried to add test cases but failed to validate the updated scrollTop property.
Adding test cases to validate setting scrollTop using mock objects should be more painless. I could provide that.
Regards Dirk

fix: $typeahead Enable scrolling of typeahead on $keydown when $typeahead.$element container has max-height css set

---

src/alert/alert.tpl.html
src/collapse/collapse.js
src/datepicker/datepicker.tpl.html
src/dropdown/docs/dropdown.demo.html
src/dropdown/dropdown.js
src/modal/modal.tpl.html
src/select/select.js
src/select/select.tpl.html
src/tab/tab.js
src/tab/tab.tpl.html
src/timepicker/timepicker.tpl.html
src/typeahead/typeahead.tpl.html

This PR comprises of fixes we've made to the source for 508 issues. 
Our product is undergoing an intense 508 validation by TPG and these are some of the first fixes we've completed. We have more fixes incoming with a major push on the Calendar component.

508 Compliance Fixes

---

src/datepicker/datepicker.js

Exempting datepicker field with timezone 'UTC' from timezone adjustment.
With existing logic, for a date fed to bsDatepicker with timezone set to UTC, it's $dateValue is being set to adjusted date with respect to client's timezone.
please find the image at [http://imgur.com/a/oj84y](url). In the image it can be seen that $dateValue value for "2017-08-20T00:00:00" is being set as "Sat Aug 19 2017 18:30:00 GMT+0530 (India Standard Time)". This shouldn't happen and so exempting adjustment when timezone is 'UTC'

fix(datepicker): Displaying Date for timezone UTC

---

src/select/select.js
src/select/test/select.spec.js

This fixes the case where ngModelOptions specify getterSetter: true. In that
case watching the ngModel attribute does nothing useful, because it will point to
a function rather than a value.
- The directive no longer deep-watches the model (this is default ngModel behaviour)
- No deep-watching should also fix #1966

fix(bsSelect): Use $viewChangeListeners instead of $watch

---

docs/dev.html
src/modal/docs/modal.demo.html
src/modal/modal.js
src/modal/modal.tpl.html
src/modal/test/modal.spec.js

508 and screen-reader support in modal.

feat(modal): 508 support in modal
